name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: /lolo
      - name: mentor
        uses: merly-ai/mentor-action@v1
        with:
          checkout-code: false
