name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: mentor
      - uses: merly-ai/mentor-action@v1
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all branches to ensure 'main' is available
          ref: main
