name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: mentor
      - uses: merly-ai/mentor-action@v1
      
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: echo "hello world"  

