name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: mentor
      uses: merly-ai/mentor-action@v1
      with:
        mm-key: {{ secret.mentor_key }}
        debug: true
      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch all branches to ensure 'main' is available
        ref: main